services:
  - type: web
    name: geekzkai-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://geekzkai.onrender.com/api