services:
  - type: web
    name: geekzkai-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/auth/callback*"
        destination: /index.html
      - type: rewrite
        source: "/*"
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://geekzkai.onrender.com/api